rocketmq:
  name-server: localhost:9876
  producer:
    group: rocketmq-spring-demo
    sendMessageTimeout: 300000
demo:
  rocketmq:
    topic: ROCKETMQ_SPRING_DEMO
logging:
  level:
    org.apache.rocketmq.spring: debug
